# Generated by Django 5.1.2 on 2025-02-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_data_added_topic_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='ex_data',
        ),
    ]
