# Generated by Django 5.1.2 on 2025-02-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_remove_topic_ex_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ex_data',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
