# Generated by Django 5.1.2 on 2025-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_topic_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='ex_data',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
